apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "falco-talon.name" . }}-rules
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falco-talon.labels" . | nindent 4 }}
data:
  rules.yaml: |-
    {{ $.Files.Get "rules.yaml" | nindent 4 }}
    {{- if .Values.config.rulesOverride }}
    {{ .Values.config.rulesOverride | nindent 4 }}
    {{- end }}
