apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falco-talon.name" . }}-config
  labels:
    {{- include "falco-talon.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    listen_address: {{ default "0.0.0.0" .Values.config.listenAddress }}
    listen_port: {{ default 2803 .Values.config.listenPort }}
    watch_rules: {{ default true .Values.config.watchRules }}
    print_all_events: {{ default false .Values.config.printAllEvents }}
    deduplication:
      leader_election: {{ default true .Values.config.deduplication.leaderElection }}
      time_window_seconds: {{ default 5 .Values.config.deduplication.timeWindowSeconds }}
    
    default_notifiers: 
    {{- range .Values.config.defaultNotifiers }}
      - {{ . -}}
    {{ end }}

    otel:
      traces_enabled: {{ default false .Values.config.otel.tracesEnabled }}
      metrics_enabled: {{ default false .Values.config.otel.metricsEnabled }}
      collector_port: {{ default 4317 .Values.config.otel.collectorPort }}
      collector_endpoint: {{ .Values.config.otel.collectorEndpoint }}
      collector_use_insecure_grpc: {{ default false .Values.config.otel.collectorUseInsecureGrpc }}
    
    notifiers:
      slack:
        webhook_url: {{ .Values.config.notifiers.slack.webhookUrl }}
        icon: {{ .Values.config.notifiers.slack.icon }}
        username: {{ .Values.config.notifiers.slack.username }}
        footer: {{ .Values.config.notifiers.slack.footer }}
        format: {{ .Values.config.notifiers.slack.format }}
      webhook:
        url: {{ .Values.config.notifiers.webhook.url }}
      smtp:
        host_port: {{ .Values.config.notifiers.smtp.hostPort }}
        from: {{ .Values.config.notifiers.smtp.from }}
        to: {{ .Values.config.notifiers.smtp.to }}
        user: {{ .Values.config.notifiers.smtp.user }}
        password: {{ .Values.config.notifiers.smtp.password }}
        format: {{ .Values.config.notifiers.smtp.format }}
        tls: {{ .Values.config.notifiers.smtp.tls }}
      loki:
        url: {{ .Values.config.notifiers.loki.url }}
        user: {{ .Values.config.notifiers.loki.user }}     
        api_key: {{ .Values.config.notifiers.loki.apiKey }}     
        tenant: {{ .Values.config.notifiers.loki.tenant }}     
        custom_headers:
          {{- range .Values.config.notifiers.loki.customHeaders }}
            - {{ . -}}
          {{ end }}   
      elasticsearch:
        url: {{ .Values.config.notifiers.elasticsearch.url }}
        create_index_template: {{ .Values.config.notifiers.loki.createIndexTemplate }}     
        number_of_shards: {{ .Values.config.notifiers.loki.numberOfShards }}     
        number_of_replicas: {{ .Values.config.notifiers.loki.numberOfReplicas }}     

    aws:
      role_arn: {{ .Values.config.aws.roleArn }}
      external_id: {{ .Values.config.aws.externalId }}
      region: {{ .Values.config.aws.region }}
      access_key: {{ .Values.config.aws.accessKey }}
      secret_key: {{ .Values.config.aws.secretKey }}
    minio:
      endpoint: {{ .Values.config.minio.endpoint }}
      access_key: {{ .Values.config.minio.accessKey }}
      secret_key: {{ .Values.config.minio.secretKey }}
      use_ssl: {{ .Values.config.minio.useSsl }}
