{{- if .Values.podSecurityPolicy.create }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "falco-talon.name" .}}
  labels:
    {{- include "falco-talon.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ template "falco-talon.name" . }}
    verbs:
      - use
{{- end }}