version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "charts/event-generator/**"
      - "charts/falco/**"
      - "charts/falco-operator/**"
      - "charts/k8s-metacollector/**"
  - package-ecosystem: "gomod"
    directories:
      - "/charts/event-generator/**"
      - "/charts/falco/**"
      - "/charts/falco-operator/**"
      - "/charts/k8s-metacollector/**"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
