{{- if .Values.defaultNetworkPolicy.enabled -}}
{{- if .Values.webui.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "falcosidekick.fullname" . }}-ui-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: ui
      app.kubernetes.io/instance: falco
      app.kubernetes.io/name: falcosidekick
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Accept Traffic on port 2802 from falcosidekick-core
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: core
              app.kubernetes.io/instance: falco
              app.kubernetes.io/name: falcosidekick
      ports:
        - port: 2802
          protocol: TCP
  egress:
    # Allow Traffic on REDIS port 6379
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: ui-redis
            app.kubernetes.io/instance: falco
            app.kubernetes.io/name: falcosidekick
      ports:
        - port: 6379
          protocol: TCP
    # Allow kube-dns resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
{{- if .Values.webui.ingress.enabled }}
---
{{- if or (.Values.defaultNetworkPolicy.webuiIngressNetworkPolicyNamespaceSelector) (.Values.defaultNetworkPolicy.webuiIngressNetworkPolicyPodSelector) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "falcosidekick.fullname" . }}-ui-network-policy-webui-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: ui
      app.kubernetes.io/instance: falco
      app.kubernetes.io/name: falcosidekick
  policyTypes:
    - Ingress
  ingress:
    # Accept Traffic on port 2802 from ingress controller
    - from:
        {{- if and (.Values.defaultNetworkPolicy.webuiIngressNetworkPolicyNamespaceSelector) (.Values.defaultNetworkPolicy.webuiIngressNetworkPolicyPodSelector) }}
        - namespaceSelector:
            matchLabels:
              {{- with .Values.defaultNetworkPolicy.webuiIngressNetworkPolicyNamespaceSelector }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
          podSelector:
            matchLabels:
              {{- with .Values.defaultNetworkPolicy.webuiIngressNetworkPolicyPodSelector }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
        {{- end }}
        {{- if and (.Values.defaultNetworkPolicy.webuiIngressNetworkPolicyNamespaceSelector) (not .Values.defaultNetworkPolicy.webuiIngressNetworkPolicyPodSelector) }}
        - namespaceSelector:
            matchLabels:
              {{- with .Values.defaultNetworkPolicy.webuiIngressNetworkPolicyNamespaceSelector }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
        {{- end }}
        {{- if and (.Values.defaultNetworkPolicy.webuiIngressNetworkPolicyPodSelector) (not .Values.defaultNetworkPolicy.webuiIngressNetworkPolicyNamespaceSelector) }}
        - podSelector:
            matchLabels:
              {{- with .Values.defaultNetworkPolicy.webuiIngressNetworkPolicyPodSelector }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
        {{- end }}
      ports:
        - port: 2802
          protocol: TCP
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}