{{- if .Values.webui.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcosidekick.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falcosidekick.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
    {{- with .Values.webui.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.webui.customAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- if .Values.webui.user }}
  FALCOSIDEKICK_UI_USER: "{{ .Values.webui.user | b64enc}}"
  {{-  end }}
  {{- if .Values.webui.redis.password }}
  FALCOSIDEKICK_UI_REDIS_PASSWORD: "{{ .Values.webui.redis.password | b64enc}}"
  {{-  end }}
{{- if eq .Values.webui.redis.existingSecret "" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcosidekick.fullname" . }}-ui-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falcosidekick.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
    {{- with .Values.webui.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.webui.customAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- if and .Values.webui.redis.enabled .Values.webui.redis.password }}
  REDIS_ARGS: "{{ printf "--requirepass %s" .Values.webui.redis.password | b64enc}}"
  REDIS_PASSWORD: "{{ .Values.webui.redis.password | b64enc }}"
  {{-  end }}
  {{- if and .Values.webui.externalRedis.password .Values.webui.externalRedis.password }}
  REDIS_PASSWORD: "{{ .Values.webui.externalRedis.password| b64enc }}"
  {{-  end }}
{{- end }}
{{- end }}
