{{- if and .Values.certs.server.key .Values.certs.server.crt .Values.certs.ca.crt }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcosidekick.fullname" . }}-certs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "falcosidekick.name" . }}
    helm.sh/chart: {{ include "falcosidekick.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ $key := .Values.certs.server.key }}
  server.key: {{ $key | b64enc | quote }}
  {{ $crt := .Values.certs.server.crt }}
  server.crt: {{ $crt | b64enc | quote }}
  falcosidekick.pem: {{ print $key $crt | b64enc | quote }}
  ca.crt: {{ .Values.certs.ca.crt | b64enc | quote }}
  ca.pem: {{ .Values.certs.ca.crt | b64enc | quote }}
{{- end }}