{{- if .Values.webui.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "falcosidekick.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "falcosidekick.name" . }}-ui
    helm.sh/chart: {{ include "falcosidekick.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-ui
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.webui.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "falcosidekick.name" . }}-ui
      app.kubernetes.io/instance: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "falcosidekick.name" . }}-ui
        app.kubernetes.io/instance: {{ .Release.Name }}-ui
      {{- if .Values.webui.podLabels }}
{{ toYaml .Values.webui.podLabels | indent 8 }}
      {{- end }}
      {{- if .Values.webui.podAnnotations }}
      annotations:
{{ toYaml .Values.webui.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "falcosidekick.fullname" . }}-ui
      {{- if .Values.webui.priorityClassName }}
      priorityClassName: "{{ .Values.webui.priorityClassName }}"
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.webui.podSecurityContext.runAsUser }}
        fsGroup: {{ .Values.webui.podSecurityContext.fsGroup }}
      containers:
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.webui.image.registry }}/{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag }}"
          imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
          args:
            - "-r"
            - {{ include "falcosidekick.fullname" . }}-ui-redis{{ if .Values.webui.redis.fullfqdn }}.{{ .Release.Namespace }}.svc.cluster.local{{ end }}:{{ .Values.webui.redis.service.port | default "6379" }}
          ports:
            - name: http
              containerPort: 2802
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.webui.resources | nindent 12 }}
      {{- with .Values.webui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "falcosidekick.fullname" . }}-ui-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "falcosidekick.name" . }}-ui-redis
    helm.sh/chart: {{ include "falcosidekick.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-ui
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  serviceName: {{ include "falcosidekick.fullname" . }}-ui-redis
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "falcosidekick.name" . }}-ui-redis
      app.kubernetes.io/instance: {{ .Release.Name }}-ui-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "falcosidekick.name" . }}-ui-redis
        app.kubernetes.io/instance: {{ .Release.Name }}-ui-redis
      {{- if .Values.webui.redis.podLabels }}
{{ toYaml .Values.webui.redis.podLabels | indent 8 }}
      {{- end }}
      {{- if .Values.webui.redis.podAnnotations }}
      annotations:
{{ toYaml .Values.webui.redis.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "falcosidekick.fullname" . }}-ui
      {{- if .Values.webui.redis.priorityClassName }}
      priorityClassName: "{{ .Values.webui.redis.priorityClassName }}"
      {{- end }}
      containers:
        - name: redis
          image: "{{ .Values.webui.redis.image.registry }}/{{ .Values.webui.redis.image.repository }}:{{ .Values.webui.redis.image.tag }}"
          imagePullPolicy: {{ .Values.webui.redis.image.pullPolicy }}
          args: []
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe: 
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5 
            periodSeconds: 5 
            timeoutSeconds: 2 
            successThreshold: 1 
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5 
            periodSeconds: 5 
            timeoutSeconds: 2 
            successThreshold: 1 
            failureThreshold: 3
          volumeMounts:
          - name: {{ include "falcosidekick.fullname" . }}-ui-redis-data
            mountPath: /data
          resources:
            {{- toYaml .Values.webui.redis.resources | nindent 12 }}
      {{- with .Values.webui.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "falcosidekick.fullname" . }}-ui-redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.webui.redis.storageSize }}
        {{- if .Values.webui.redis.storageClass }}
        storageClassName: {{ .Values.webui.redis.storageClass }}
        {{- end }}
{{- end }}