{{- if .Values.webui.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "falcosidekick.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "falcosidekick.name" . }}-ui
    helm.sh/chart: {{ include "falcosidekick.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-ui
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "falcosidekick.name" . }}-ui
      app.kubernetes.io/instance: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "falcosidekick.name" . }}-ui
        app.kubernetes.io/instance: {{ .Release.Name }}-ui
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.webui.priorityClassName }}
      priorityClassName: "{{ .Values.webui.priorityClassName }}"
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.webui.podSecurityContext.runAsUser }}
        fsGroup: {{ .Values.webui.podSecurityContext.fsGroup }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.webui.image.registry }}/{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag }}"
          imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
          args:
            - "-r"
            - "{{ .Values.webui.retention }}"
          {{- if .Values.webui.darkmode }}
            - "-d"
          {{- end }}
          ports:
            - name: http
              containerPort: 2802
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            # - name: RETENTION
            #   value: {{ .Values.webui.retention | quote }}
          resources:
            {{- toYaml .Values.webui.resources | nindent 12 }}
      {{- with .Values.webui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
