{{- if eq .Values.config.existingSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcosidekick.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "falcosidekick.name" . }}
    helm.sh/chart: {{ include "falcosidekick.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  # Slack Output
  SLACK_WEBHOOKURL: "{{ .Values.config.slack.webhookurl | b64enc }}"
  SLACK_OUTPUTFORMAT: "{{ .Values.config.slack.outputformat | b64enc }}"
  SLACK_FOOTER: "{{ .Values.config.slack.footer | b64enc }}"
  SLACK_ICON: "{{ .Values.config.slack.icon | b64enc }}"
  SLACK_USERNAME: "{{ .Values.config.slack.username | b64enc }}"
  SLACK_MINIMUMPRIORITY: "{{ .Values.config.slack.minimumpriority | b64enc }}"
  SLACK_MESSAGEFORMAT: "{{ .Values.config.slack.messageformat | b64enc }}"

  # RocketChat Output
  ROCKETCHAT_WEBHOOKURL: "{{ .Values.config.rocketchat.webhookurl | b64enc }}"
  ROCKETCHAT_OUTPUTFORMAT: "{{ .Values.config.rocketchat.outputformat | b64enc }}"
  ROCKETCHAT_ICON: "{{ .Values.config.rocketchat.icon | b64enc }}"
  ROCKETCHAT_USERNAME: "{{ .Values.config.rocketchat.username | b64enc }}"
  ROCKETCHAT_MINIMUMPRIORITY: "{{ .Values.config.rocketchat.minimumpriority | b64enc }}"
  ROCKETCHAT_MESSAGEFORMAT: "{{ .Values.config.rocketchat.messageformat | b64enc }}"

  # Mattermost Output
  MATTERMOST_WEBHOOKURL: "{{ .Values.config.mattermost.webhookurl | b64enc }}"
  MATTERMOST_OUTPUTFORMAT: "{{ .Values.config.mattermost.outputformat | b64enc }}"
  MATTERMOST_FOOTER: "{{ .Values.config.mattermost.footer | b64enc }}"
  MATTERMOST_ICON: "{{ .Values.config.mattermost.icon | b64enc }}"
  MATTERMOST_USERNAME: "{{ .Values.config.mattermost.username | b64enc }}"
  MATTERMOST_MINIMUMPRIORITY: "{{ .Values.config.mattermost.minimumpriority | b64enc }}"
  MATTERMOST_MESSAGEFORMAT: "{{ .Values.config.mattermost.messageformat | b64enc }}"

  # Teams Output
  TEAMS_WEBHOOKURL: "{{ .Values.config.teams.webhookurl | b64enc }}"
  TEAMS_OUTPUTFORMAT: "{{ .Values.config.teams.outputformat | b64enc }}"
  TEAMS_ACTIVITYIMAGE: "{{ .Values.config.teams.activityimage | b64enc }}"
  TEAMS_MINIMUMPRIORITY: "{{ .Values.config.teams.minimumpriority | b64enc }}"

  # Datadog Output
  DATADOG_APIKEY: "{{ .Values.config.datadog.apikey | b64enc }}"
  DATADOG_MINIMUMPRIORITY: "{{ .Values.config.datadog.minimumpriority | b64enc }}"

  # AlertManager Output
  ALERTMANAGER_HOSTPORT: "{{ .Values.config.alertmanager.hostport | b64enc }}"
  ALERTMANAGER_MINIMUMPRIORITY: "{{ .Values.config.alertmanager.minimumpriority | b64enc }}"

  # InfluxDB Output
  INFLUXDB_USER: "{{ .Values.config.influxdb.user | b64enc }}"
  INFLUXDB_PASSWORD: "{{ .Values.config.influxdb.password | b64enc }}"
  INFLUXDB_HOSTPORT: "{{ .Values.config.influxdb.hostport | b64enc }}"
  INFLUXDB_MINIMUMPRIORITY: "{{ .Values.config.influxdb.minimumpriority | b64enc }}"
  INFLUXDB_DATABASE: "{{ .Values.config.influxdb.database | b64enc }}"

  # AWS Output
  AWS_ACCESSKEYID: "{{ .Values.config.aws.accesskeyid | b64enc }}"
  AWS_SECRETACCESSKEY: "{{ .Values.config.aws.secretaccesskey | b64enc }}"
  AWS_REGION: "{{ .Values.config.aws.region | b64enc }}"
  AWS_LAMBDA_FUNCTIONNAME: "{{ .Values.config.aws.lambda.functionname | b64enc }}"
  AWS_LAMBDA_MINIMUMPRIORITY: "{{ .Values.config.aws.lambda.minimumpriority | b64enc }}"
  AWS_CLOUDWATCHLOGS_LOGGROUP: "{{ .Values.config.aws.cloudwatchlogs.loggroup | b64enc }}"
  AWS_CLOUDWATCHLOGS_LOGSTREAM: "{{ .Values.config.aws.cloudwatchlogs.logstream | b64enc }}"
  AWS_CLOUDWATCHLOGS_MINIMUMPRIORITY: "{{ .Values.config.aws.cloudwatchlogs.minimumpriority | b64enc }}"
  AWS_SNS_TOPICARN: "{{ .Values.config.aws.sns.topicarn | b64enc }}"
  AWS_SNS_RAWJSON: "{{ .Values.config.aws.sns.rawjson| printf "%t" | b64enc }}"
  AWS_SNS_MINIMUMPRIORITY: "{{ .Values.config.aws.sns.minimumpriority | b64enc }}"
  AWS_SQS_URL: "{{ .Values.config.aws.sqs.url | b64enc }}"
  AWS_SQS_MINIMUMPRIORITY: "{{ .Values.config.aws.sqs.minimumpriority | b64enc }}"

  # SMTP Output
  SMTP_USER: "{{ .Values.config.smtp.user | b64enc }}"
  SMTP_PASSWORD: "{{ .Values.config.smtp.password | b64enc }}"
  SMTP_HOSTPORT: "{{ .Values.config.smtp.hostport | b64enc }}"
  SMTP_FROM: "{{ .Values.config.smtp.from | b64enc }}"
  SMTP_TO: "{{ .Values.config.smtp.to | b64enc }}"
  SMTP_OUTPUTFORMAT: "{{ .Values.config.smtp.outputformat | b64enc }}"
  SMTP_MINIMUMPRIORITY: "{{ .Values.config.smtp.minimumpriority | b64enc }}"

  # OpsGenie Output
  OPSGENIE_APIKEY: "{{ .Values.config.opsgenie.apikey | b64enc }}"
  OPSGENIE_REGION: "{{ .Values.config.opsgenie.region | b64enc }}"
  OPSGENIE_MINIMUMPRIORITY: "{{ .Values.config.opsgenie.minimumpriority | b64enc }}"

  # Discord Output
  DISCORD_WEBHOOKURL: "{{ .Values.config.discord.webhookurl | b64enc }}"
  DISCORD_ICON: "{{ .Values.config.discord.icon | b64enc }}"
  DISCORD_MINIMUMPRIORITY: "{{ .Values.config.discord.minimumpriority | b64enc }}"

  # GCP Output
  GCP_CREDENTIALS: "{{ .Values.config.gcp.credentials | b64enc }}"
  GCP_PUBSUB_PROJECTID: "{{ .Values.config.gcp.pubsub.projectid | b64enc }}"
  GCP_PUBSUB_TOPIC: "{{ .Values.config.gcp.pubsub.topic | b64enc }}"
  GCP_PUBSUB_MINIMUMPRIORITY: "{{ .Values.config.gcp.pubsub.minimumpriority | b64enc }}"

  # GoogleChat Output
  GOOGLECHAT_WEBHOOKURL: "{{ .Values.config.googlechat.webhookurl | b64enc }}"
  GOOGLECHAT_OUTPUTFORMAT: "{{ .Values.config.googlechat.outputformat | b64enc }}"
  GOOGLECHAT_MINIMUMPRIORITY: "{{ .Values.config.googlechat.minimumpriority | b64enc }}"
  GOOGLECHAT_MESSAGEFORMAT: "{{ .Values.config.googlechat.messageformat | b64enc }}"

  # ElasticSearch Output
  ELASTICSEARCH_HOSTPORT: "{{ .Values.config.elasticsearch.hostport | b64enc }}"
  ELASTICSEARCH_INDEX: "{{ .Values.config.elasticsearch.index | b64enc }}"
  ELASTICSEARCH_TYPE: "{{ .Values.config.elasticsearch.type | b64enc }}"
  ELASTICSEARCH_MINIMUMPRIORITY: "{{ .Values.config.elasticsearch.minimumpriority | b64enc }}"

  # Loki Output
  LOKI_HOSTPORT: "{{ .Values.config.loki.hostport | b64enc }}"
  LOKI_MINIMUMPRIORITY: "{{ .Values.config.loki.minimumpriority | b64enc }}"

  # Nats Output
  NATS_HOSTPORT: "{{ .Values.config.nats.hostport | b64enc }}"
  NATS_MINIMUMPRIORITY: "{{ .Values.config.nats.minimumpriority | b64enc }}"

  # Stan Output
  STAN_HOSTPORT: "{{ .Values.config.stan.hostport | b64enc }}"
  STAN_CLUSTERID: "{{ .Values.config.stan.clusterid | b64enc }}"
  STAN_CLIENTID: "{{ .Values.config.stan.clientid | b64enc }}"
  STAN_MINIMUMPRIORITY: "{{ .Values.config.stan.minimumpriority | b64enc }}"

  # Statsd
  STATSD_FORESPACE: "{{ .Values.config.statsd.namespace | b64enc }}"

  # Dogstatsd
  DOGSTATSD_FORWARDER: "{{ .Values.config.dogstatsd.forwarder | b64enc }}"
  DOGSTATSD_NAMESPACE: "{{ .Values.config.dogstatsd.namespace | b64enc }}"
  DOGSTATSD_TAGS: "{{ .Values.config.dogstatsd.tags | b64enc }}"

  # WebHook Output
  WEBHOOK_ADDRESS: "{{ .Values.config.webhook.address | b64enc }}"
  WEBHOOK_CUSTOMHEADERS: "{{ .Values.config.webhook.customHeaders | b64enc }}"
  WEBHOOK_MINIMUMPRIORITY: "{{ .Values.config.webhook.minimumpriority | b64enc }}"

  # Azure Output
  AZURE_EVENTHUB_NAME: "{{ .Values.config.azure.eventHub.name | b64enc }}"
  AZURE_EVENTHUB_NAMESPACE: "{{ .Values.config.azure.eventHub.namespace | b64enc }}"
  AZURE_EVENTHUB_MINIMUMPRIORITY: "{{ .Values.config.azure.eventHub.minimumpriority | b64enc }}"

  # Kafka Output
  KAFKA_URL: "{{ .Values.config.kafka.url | b64enc }}"
  KAFKA_TOPIC: "{{ .Values.config.kafka.topic | b64enc }}"
  KAFKA_PARTITION: "{{ .Values.config.kafka.partition | b64enc }}"
  KAFKA_MINIMUMPRIORITY: "{{ .Values.config.kafka.minimumpriority | b64enc }}"

  # PagerDuty Output
  PAGERDUTY_APIKEY: "{{ .Values.config.pagerduty.apikey | b64enc }}"
  PAGERDUTY_SERVICE: "{{ .Values.config.pagerduty.service | b64enc }}"
  PAGERDUTY_ASSIGNEE: "{{ .Values.config.pagerduty.assignee | b64enc }}"
  PAGERDUTY_ESCALATION_POLICY: "{{ .Values.config.pagerduty.escalationpolicy | b64enc }}"
  PAGERDUTY_MINIMUMPRIORITY: "{{ .Values.config.pagerduty.minimumpriority | b64enc }}"
  
  # Kubeless Output
  KUBELESS_FUNCTION: "{{ .Values.config.kubeless.function | b64enc }}"
  KUBELESS_NAMESPACE: "{{ .Values.config.kubeless.namespace | b64enc }}"
  KUBELESS_PORT: "{{ .Values.config.kubeless.port | toString | b64enc }}"
  KUBELESS_MINIMUMPRIORITY: "{{ .Values.config.kubeless.minimumpriority | b64enc }}"
{{- end }}
