version: 2.1
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          command: |
            shellcheck -x tests/e2e-kind.sh
            shellcheck -x .circleci/install_tools.sh
            shellcheck -x .circleci/release.sh

  lint-charts:
    docker:
      - image: quay.io/helmpack/chart-testing:latest
    steps:
      - checkout
      - run:
          name: lint
          command: ct lint --config tests/ct.yaml

  install-charts:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - run:
          command: tests/e2e-kind.sh
          no_output_timeout: 1h

  release-charts:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: checkout
          command: |
            git clone https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git .
      - run:
          name: release
          command: |
            echo "export CR_REPO_URL=https://falcosecurity.github.io/charts" >> $BASH_ENV
            echo "export GIT_USERNAME=$CIRCLE_PROJECT_USERNAME" >> $BASH_ENV
            echo "export GIT_REPOSITORY_NAME=$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV
            .circleci/install_tools.sh
            .circleci/release.sh

workflows:
  version: 2
  release:
    jobs:
      - lint-scripts:
          filters:
            branches:
              ignore: gh-pages
      - lint-charts:
          filters:
            branches:
              ignore: gh-pages
      - install-charts:
          filters:
            branches:
              ignore: gh-pages
          requires:
            - lint-scripts
            - lint-charts
      - release-charts:
          context: falco
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master