version: 2.1
jobs:
  lint-charts:
    docker:
        - image: quay.io/helmpack/chart-testing:latest
    steps:
      - checkout
      - run:
          name: lint
          command: .circleci/lint.sh
  release-charts:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: checkout
          command: |
            git clone https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git .
      - run:
          name: release
          command: |
            echo "export CR_REPO_URL=https://falcosecurity.github.io/charts" >> $BASH_ENV
            echo "export GIT_USERNAME=$CIRCLE_PROJECT_USERNAME" >> $BASH_ENV
            echo "export GIT_REPOSITORY_NAME=$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV
            .circleci/install_tools.sh
            .circleci/release.sh

workflows:
  version: 2
  release:
    jobs:
      - "lint-charts"
      - release-charts:
          context: falco
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
