apiVersion: v1
name: falcosidekick
version: 0.1.20
appVersion: 2.14.0
description: A simple daemon to help you with falco's outputs
keywords:
  - monitoring
  - security
  - alerting
  - metric
home: https://falco.org
icon: https://raw.githubusercontent.com/falcosecurity/falcosidekick/master/imgs/falcosidekick.png
sources:
  - https://github.com/falcosecurity/falcosidekick
maintainers:
  - name: Issif
    email: issig+github@gadz.org