apiVersion: v1
appVersion: 2.19.1
description: A simple daemon to help you with falco's outputs
icon: https://raw.githubusercontent.com/falcosecurity/falcosidekick/master/imgs/falcosidekick_color.png
name: falcosidekick
version: 0.1.37
keywords:
  - monitoring
  - security
  - alerting
home: https://github.com/falcosecurity/falcosidekick
sources:
  - https://github.com/falcosecurity/falcosidekick
maintainers:
  - name: Issif
    email: cncf-falco-dev@lists.cncf.io
