{{- if .Values.podSecurityPolicy.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "falco-exporter.podSecurityPolicyName" . }}
  labels:
    {{- include "falco-exporter.labels" . | nindent 4 }}
  {{- with .Values.podSecurityPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "falco-exporter.podSecurityPolicyName" . }}
    verbs:
      - use
{{- end -}}