{{- if .Values.podSecurityPolicy.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "falco-exporter.podSecurityPolicyName" . }}
  labels:
    {{- include "falco-exporter.labels" . | nindent 4 }}
  {{- with .Values.podSecurityPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "falco-exporter.podSecurityPolicyName" . }}
roleRef:
  kind: Role
  name: {{ include "falco-exporter.podSecurityPolicyName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}