apiVersion: v2
name: falco
version: 1.7.4
appVersion: 0.27.0
description: Falco
keywords:
  - monitoring
  - security
  - alerting
  - metric
  - troubleshooting
  - run-time
home: https://falco.org
icon: https://falco.org/images/logos/falco-logo.png
sources:
  - https://github.com/falcosecurity/falco
maintainers:
  - name: The Falco Authors
    email: cncf-falco-dev@lists.cncf.io
dependencies:
  - name: falcosidekick
    version: "0.2.6"
    condition: falcosidekick.enabled
    repository: https://falcosecurity.github.io/charts
