apiVersion: v1
name: falco
version: 1.5.5
appVersion: 0.26.2
description: Falco
keywords:
  - monitoring
  - security
  - alerting
  - metric
  - troubleshooting
  - run-time
home: https://falco.org
icon: https://falco.org/images/logos/falco-logo.png
sources:
  - https://github.com/falcosecurity/falco
maintainers:
  - name: The Falco Authors
    email: cncf-falco-dev@lists.cncf.io
