apiVersion: v1
kind: Service
metadata:
  name: {{ include "falco-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falco-operator.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: falco
    control-plane: falco-operator
spec:
  selector:
    {{- include "falco-operator.selectorLabels" . | nindent 4 }}
    control-plane: falco-operator
    app.kubernetes.io/part-of: falco
  ports:
    - name: artifact-server
      port: 8082
      targetPort: artifact-server
      protocol: TCP
