apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "falco.fullname" . }}
  namespace: {{ include "falco.namespace" . }}
  labels:
    {{- include "falco.labels" . | nindent 4 }}
data:
  falco.yaml: |-
    {{- include "falco.falcosidekickConfig" . }}
    {{- include "k8smeta.configuration" . -}}
    {{- include "falco.engineConfiguration" . -}}
    {{- include "falco.metricsConfiguration" . -}}
    {{- include "falco.containerEnginesConfiguration" . -}}
    {{- toYaml .Values.falco | nindent 4 }}
