---
# Source: falco/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: RELEASE-NAME-falco
  labels:
    app: RELEASE-NAME-falco
    chart: "falco-1.2.1"
    release: "RELEASE-NAME"
    heritage: "Helm"
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-falco
    namespace: default
roleRef:
  kind: ClusterRole
  name: RELEASE-NAME-falco
  apiGroup: rbac.authorization.k8s.io
