---
# Source: falco-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-falco-exporter
  annotations:
    prometheus.io/port: "9376"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: falco-exporter
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.3.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: falco-exporter-0.3.1
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 9376
      targetPort: 9376
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: falco-exporter
    app.kubernetes.io/instance: RELEASE-NAME
