apiVersion: v2
name: falco-operator
description: A Helm chart for deploying the Falco Operator
home: https://github.com/falcosecurity/falco-operator
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/falco/horizontal/color/falco-horizontal-color.svg
sources:
  - https://github.com/falcosecurity/falco-operator
keywords:
  - falco
  - security
  - monitoring
  - operator
maintainers:
  - name: The Falco Authors
    email: cncf-falco-dev@lists.cncf.io
type: application
version: 0.2.0
appVersion: "0.3.0"
