{{- if and .Values.falco.grpc.enabled (not .Values.falco.grpc.unixSocketPath)}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "falco.fullname" . }}-grpc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falco.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "falco.fullname" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.falco.grpc.listenPort }}
{{- end }}