name: Sync from upstream

on:
  schedule:
    - cron: '0 7 */7 * *' # At 07:00 on every 7th day-of-month

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-app-falco-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync falco from upstream
        uses: giantswarm/subtree-util@v0.1.2
        with:
          target_github_token: ${{ secrets.ARCHITECT_BOT_GITHUB_REPO_SYNC_TOKEN }}
          target_repository: giantswarm/falco-app
          target_path: helm/falco-app/charts/falco
          source_path: falco

  sync-app-falco-exporter-repository:
    runs-on: ubuntu-latest
    needs: sync-app-falco-repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync falco-exporter from upstream
        uses: giantswarm/subtree-util@v0.1.2
        with:
          target_github_token: ${{ secrets.ARCHITECT_BOT_GITHUB_REPO_SYNC_TOKEN }}
          target_repository: giantswarm/falco-app
          target_path: helm/falco-app/charts/falco-exporter
          source_path: falco-exporter

  sync-app-falcosidekick-repository:
    runs-on: ubuntu-latest
    needs: sync-app-falco-exporter-repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync falcosidekick from upstream
        uses: giantswarm/subtree-util@v0.1.2
        with:
          target_github_token: ${{ secrets.ARCHITECT_BOT_GITHUB_REPO_SYNC_TOKEN }}
          target_repository: giantswarm/falco-app
          target_path: helm/falco-app/charts/falcosidekick
          source_path: falcosidekick
